echo "domainfinder をビルドします..."
go build -o domainfinder.exe
echo "synonyms をビルドします..."
cd "../synonyms"
go build -o "../domainfinder/lib/synonyms.exe"
cd "../available"
echo "available をビルドします..."
go build -o "../domainfinder/lib/available.exe"
cd "../sprinkle"
echo "sprinkle をビルドします..."
go build -o "../domainfinder/lib/sprinkle.exe"
cd "../coolify"
echo "coolify をビルドします..."
go build -o "../domainfinder/lib/coolify.exe"
cd "../domainify"
echo "domainify をビルドします..."
go build -o "../domainfinder/lib/domainify.exe"
cd "../domainfinder"
echo "完了"
